config/routes.rb
Rails.application.routes.draw do
  root 'teams#show_user_team'

  get '/register', to: 'teams#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :teams do
    resources :categories
  end

  resources :users do
    resources :cycles do
      resources :workouts, only: [:new, :create, :edit, :update]
    end
  end
  resources :categories

end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  has_secure_password validations: false

  validates :name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email, case_sensitive: false
  validates :role, presence: true
  before_save :make_email_lowercase

  has_many :cycles
  belongs_to :team

  sluggable_column :name

  def make_email_lowercase
    self.email = self.email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user_or_admin, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.team = current_user.team
    if @user.save
      flash[:success] = "User created!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Invalid update."
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User profile updated."
      redirect_to user_path(@user)
    else
      flash[:alert] = "Invalid update attempt."
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def require_same_user_or_admin
    unless (current_user == @user) || (current_user.role == "Admin")
      error_message
    end
  end

  def error_message
    flash[:alert] = "You cannot do that."
    redirect_to root_path
  end
end

app/views/users/_basic_user_info.html.erb
<% label_type = (user.role == "Coach" ? "alert" : "success") %>
<% label_type = "warning" if user.role == "Admin" %>

<div class="panel">
  <% if logged_in? and current_user == user %>
    <%= link_to edit_user_path(user), class: "right" do %>
      <i class="fi-pencil" title="Edit"></i>
    <% end %>
  <% end %>
  <p>Name: <%= user.name %></p>
  <p>Email: <%= user.email %></p>
  <span class="label <%= label_type %> radius"><%= user.role %></span>
  
</div>

app/views/users/_form.html.erb
<% if logged_in? %>
  <% role_selection = if current_user == @user and current_user.role == "Admin" %>
    <%["Admin"]%>
  <% elsif current_user.role == "Admin" %>
    <% [ "Athlete", "Coach", "Admin" ] %>
  <% elsif current_user == @user and current_user.role == "Coach" %>
    <% [ "Coach" ] %>
  <% elsif current_user.role == "Coach" %>
    <% ["Athlete", "Coach"] %>
  <% else %>
    <% ["Athlete"] %>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= render "shared/errors", object: @user %>
  <div class="small-4">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="small-4">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="small-4">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="small-4">
    <%= f.label :role %>
    <%= f.select :role, role_selection %>
  </div>
  <div>
    <%= f.submit submit_text, class: "button small radius" %>
    <%= link_to "Cancel", root_path, class: "button small radius secondary" %>
  </div>
<% end %>

app/views/users/_users_table.html.erb
<% users = users.select{|x| x.role == role} %>

<h4><%= pluralize(users.size, role) %></h4>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <% if logged_in? and (current_user.role == role or current_user.role == "Admin" ) %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% users.select{|x| x.role == role}.each do |user| %>
      <% role_type = (user.role == "Coach" ? "alert" : "success") %>
      <tr>
        <td><%= link_to user.name, user_path(user), title: "View Profile" %></td>
        <td><span class="label <%= role_type%> radius"><%= user.role %></span></td>
        <% if  logged_in? and (current_user == user or current_user.role == "Admin")%>
        <td>
          <%= link_to edit_user_path(user) do %>
            <i class="fi-pencil" title="Edit"></i>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<%= render "shared/content_title", title: "Edit User" %>

<%= render "form", submit_text: "Update" %>

app/views/users/index.html.erb
<%= render "shared/content_title", title: "Users Index" %>

<% if logged_in? && ["Coach", "Admin"].include?(current_user.role) %>
  <%= link_to "Add User", new_user_path, class: "button medium radius" %>
<% end %>

<ul class="small-block-grid-1 medium-block-grid-2" data-equalizer >
  <li>
    <div class="panel callout" data-equalizer-watch>
      <%= render "users_table", users: @users, role: "Athlete" %>
    </div>
  </li>
  <li>
    <div class="panel" data-equalizer-watch>
      <%= render "users_table", users: @users, role: "Coach" %>
    </div>
  </li>
</ul>

app/views/users/new.html.erb
<%= render "shared/content_title", title: "New User" %>

<%= render "form", submit_text: "Create" %>

app/views/users/show.html.erb
<% cycles = @user.cycles.sort{|x,y| x.start_date <=> y.start_date} %>

<%= render "shared/content_title", title: "User Profile" %>

<%= render "basic_user_info", user: @user %>
<% if logged_in? and (current_user == @user or ["Coach", "Admin"].include?(current_user.role)) %>
<%= link_to "Add Cycle", new_user_cycle_path(@user), class: "button tiny radius success" %>
<% end %>
<br>
<strong><%= pluralize(@user.cycles.size,"Cycle")%></strong>
<div class="row">
  <% cycles.each do |cycle| %>
    <div class="small-4 column <%= cycle == cycles.last ? 'end' : ''%>">
      <%= render "cycles/cycle_preview", cycle: cycle %>
    </div>
  <% end %>
</div>