config/routes.rb
Rails.application.routes.draw do
  root 'teams#show_user_team'

  get '/register', to: 'teams#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :teams do
    resources :categories
  end

  resources :users do
    resources :cycles do
      resources :workouts, only: [:new, :create, :edit, :update]
    end
  end
  resources :categories

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  belongs_to :user
  has_many :workouts

  validates :length_of_time, presence: true
  validates :length_of_time_units, presence: true
  validates :start_date, presence: true
  validates_uniqueness_of :start_date, scope: :user_id

  def end_date
    start = self.start_date
    time = self.length_of_time
    multi = 1
    if self.length_of_time_units == "Days"
      multi = 1
    else
      multi = 7
    end
    return start + time * multi
  end

  def sort_workouts_for_show
    self.workouts.sort do |x,y|
      if x.date == y.date
        x.am_pm <=> y.am_pm
      else
        x.date <=> y.date
      end
    end
  end
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  before_action :set_cycle, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]
  before_action :user_must_be_logged_in_the_user_the_coach_or_admin, only: [:new, :create, :edit, :update]
  def show
  end

  def new
  end

  def create
    @cycle_form.submit(cycle_params)
    if @cycle_form.save
      flash[:success] = "Cycle created successfully."
      redirect_to user_cycle_path(@cycle.user, @cycle)
    else
      flash[:alert] = "Invalid submission."
      render :new
    end
  end

  def edit
  end

  def update
    @cycle_form.submit(cycle_params)
    if @cycle_form.save
      flash[:success] = "Cycle updated."
      redirect_to user_cycle_path(@cycle.user, @cycle)
    else
      flash[:alert] = "Invalid submission."
      render :edit
    end
  end


  private
  def set_cycle
    @cycle = Cycle.find(params[:id])
  end
  def cycle_params
    params.require(:cycle).permit(:length_of_time, :length_of_time_units, :description, :start_date, workouts_attributes: [:id, :date, :am_pm])
  end
  def create_new_form
    user = User.find_by(slug: params[:user_id])
    @cycle = Cycle.new(length_of_time: 4, length_of_time_units: "weeks")
    @cycle.user = user
    @cycle_form = CycleForm.new(@cycle)
  end
  def create_edit_form
    @cycle_form = CycleForm.new(@cycle)
  end
  def user_must_be_logged_in_the_user_the_coach_or_admin
    unless logged_in? and (current_user.role == "Admin" or current_user == @cycle.user or current_user.role == "Coach")
      error_message
    end
  end
  def error_message
    flash[:alert] = "Access denied."
    redirect_to root_path
  end
end

app/views/cycles/_cycle_preview.html.erb
<div class="panel">
  <% if logged_in? and user_is_current_user_coach_or_admin?(cycle.user) %>
    <%= link_to edit_user_cycle_path(cycle.user, cycle), class: "right", title: "Edit" do %>
      <i class="fi-pencil"></i>
    <% end %>
  <% end %>

  <h5><%= link_to cycle.description, user_cycle_path(cycle.user, cycle) %></h5>
  <hr>
  Start Date: <%= format_date(cycle.start_date) %><br>
  Length of Cycle: <%= "#{cycle.length_of_time} #{cycle.length_of_time_units}" %><br>
  End Date: <%= format_date(cycle.end_date) %>
  <hr>
  <%= pluralize(cycle.workouts.size, "Workout") %> Listed

</div>

app/views/cycles/_form.html.erb
<%= form_for [User.find_by(slug: params[:user_id]), @cycle_form] do |f| %>
  <%= render "shared/errors", object: @cycle_form %>

  <div class="row">
    <div class="large-3 column">
      <%= f.label :start_date %>
      <%= f.date_field :start_date %>
    </div>
    <div class="large-3 column">
      <%= f.label :legnth_of_time %>
      <%= f.number_field :length_of_time, in: 1..100, step: 1, placeholder: 4, size: 5 %>
    </div>
    <div class="large-2 column end">
      <%= f.label :length_of_time_units, "Time Units" %>
      <%= f.select :length_of_time_units, ["Weeks", "Days"]%>
    </div>
  </div>
  <div class="row">
    <div class="large-8 column end">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: "Describe what this cycle is, e.g. 'Competition Preparation' or 'General Strength Cycle'"%>
    </div>
  </div>

  <br>
  <strong>Workouts</strong>
  <hr>
  <%= f.fields_for :workouts do |workouts_fields| %>
    <%= render "workout_fields", f: workouts_fields %>
  <% end %>
  <div class="row">
    <div class="large-3 column end">
      <%= link_to_add_association "Add Workout", f, :workouts, class: "button radius small success" %>
    </div>
  </div>
  <br>

  <div class="row collapse">
    <div class="large-2 column">
      <%= f.submit submit_text, class: "button medium radius" %>
    </div>
    <div class="large-2 column end">
      <%= link_to "Cancel", user_path(@cycle.user), class: "button medium radius secondary" %>
    </div>
  </div>
<% end %>

app/views/cycles/_workout_fields.html.erb
<div class="nested-fields" data-equalizer>
  <div class="row">
    <div class="medium-5 column">
      <div class="row">
        <div class="medium-3 column">
          <%= f.label :date %>
        </div>
        <div class="medium-9 column end">
          <%= f.date_field :date%>
        </div>
      </div>
      <div class="row">
        <div class="medium-3 column">
          <%= f.label :am_pm, "AM or PM?" %>
        </div>
        <div class="medium-9 column end">
          <%= f.select :am_pm, ["AM", "PM"] %>
        </div>
      </div>
    </div>
    <div class="medium-1 column end">
      <%= link_to_remove_association "<i class='fi-x'></i>".html_safe, f, class: "button small radius alert", style: "margin-top:1.1rem;", data: {confirm: "Are you sure?"} %>
    </div>
  </div>
</div>
<hr>

app/views/cycles/edit.html.erb
<%= render "shared/content_title", title: "Edit Cycle" %>

<%= render "form", submit_text: "Update" %>

app/views/cycles/new.html.erb
<% user = User.find_by(slug: params[:user_id]) %>
<%= render "shared/content_title", title: "#{link_to user.name, user_path(user)} > New Cycle".html_safe %>

<%= render "form", submit_text: "Create" %>

app/views/cycles/show.html.erb
<%= render "shared/content_title", title: "#{link_to @cycle.user.name, user_path(@cycle.user)} > #{@cycle.length_of_time} #{@cycle.length_of_time_units} Cycle, #{format_date(@cycle.start_date)}".html_safe %>
<h4><%= @cycle.description %> Cycle</h4>

<% if logged_in? and user_is_current_user_coach_or_admin?(@cycle.user) %>
  <%= link_to "Edit Cycle", edit_user_cycle_path(@cycle.user, @cycle), class: "button radius warning small right" %>
  <%= link_to "Add Workout", new_user_cycle_workout_path(@cycle.user, @cycle), class: "button radius success small" %>
<% end %>

<ul class="accordion" data-accordion>
  <% count = 1 %>
  <% @cycle.sort_workouts_for_show.each do |workout| %>
    <li class="accordion-navigation">
      <a href='#workout-<%= "#{workout.date}-#{count}"%>'><%= format_date(workout.date) %>: <%= workout.am_pm %> (Click to See)</a>
      <div id='<%= "workout-#{workout.date}-#{count}"%>' class="content">
        <%= render "workouts/workout_preview", workout: workout %>
      </div>
      <% count += 1 %>
    </li>
  <% end %>
</ul>

<script>
  $(document).foundation({
    accordion: {
      callback : function (accordion) {
        console.log(accordion);
      }
    }
  });
</script>