config/routes.rb
Rails.application.routes.draw do
  root 'teams#show_user_team'

  get '/register', to: 'teams#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :teams do
    resources :categories
  end

  resources :users do
    resources :cycles do
      resources :workouts, only: [:new, :create, :edit, :update]
    end
  end
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :team

  has_many :subcategories, dependent: :destroy
  has_many :exercises, through: :subcategories

  belongs_to :team

  def self.for_select
    self.where(team: @workout.user.team).sort{|x,y| x.name <=> y.name}.map{|x| [x, x.exercises.map{|y| [y.name, y.id]}]}
  end

  def self.for_group_select(workout)
    self.where(team: workout.cycle.user.team).sort{|x,y| x.name <=> y.name}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]
  before_action :require_user, only: [:show, :new, :create, :edit, :update]
  def show
  end

  def new
  end

  def create
    @category_form.submit(category_params)

    if @category_form.save
      flash[:success] = "Category created successfully."
      redirect_to @category_form
    else
      flash[:alert] = "Invalid submission."
      render :new
    end
  end

  def edit
  end

  def update
    @category_form.submit(category_params)
    if @category_form.save
      flash[:success] = "Category updated!"
      redirect_to @category_form
    else
      flash[:alert] = "Invalid submission."
      render :edit
    end
  end


  private
  def set_category
    @category = Category.find(params[:id])
  end
  def category_params
    params.require(:category).permit(:name, :abbreviation, subcategories_attributes: [:id, :name, :rank, :_destroy, exercises_attributes: [:id, :name, :nickname, :_destroy]])
  end

  def create_new_form
    category = Category.new
    category.team = current_user.team
    @category_form = CategoryForm.new(category)
  end

  def create_edit_form
    @category_form = CategoryForm.new(@category)
  end
  def require_user
    unless logged_in?
      error_message
    end
  end
  def error_message
    flash[:alert] = "Access denied."
    redirect_to root_path
  end
end

app/views/categories/_exercise_fields.html.erb
<div class="row nested-fields">
  <div class="large-3 column">
    <%= f.label :name, "Full Name" %>
    <%= f.text_field :name %>
  </div>
  <div class="large-2 column">
    <%= f.label :nickname, "Nickname" %>
    <%= f.text_field :nickname %>
  </div>

  <div class="large-1 end column">
    <%= link_to_remove_association "<i class='fi-x'></i>".html_safe, f, class: "button radius tiny alert", data: {confirm: "Are you sure? Note: won't be deleted until you select update."} %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_for @category_form do |f| %>
  <%= render "shared/errors", object: @category_form %>


  <h4><span data-tooltip aria-haspopup="true" class="has-tip" title="A Category is intended to be the highest level grouping of exercises. An example would be Olympic Lifts or Snatch. It depends on how you wish to organize the subcategories.">Category</span></h4>
  <div class="small-4">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="small-4">
    <%= f.label :abbreviation %>
    <%= f.text_field :abbreviation %>
  </div>
  <hr>

  <h4><span data-tooltip aria-haspopup="true" class="has-tip" title="A subcategory is intended to be the lowest level grouping of exercises. If the parent category is Olympic Lifts then subcategories might be Snatch and Clean. If the parent category is Conditioning subcategories might be Running, Swimming, or Biking.">Subcategory</span></h4>
  <%= f.fields_for :subcategories do |s| %>
    <%= render "subcategory_fields", f: s %>
  <% end %>

  <hr>
  <div class="row">
    <%= link_to_add_association "Add Subcategory", f, :subcategories, class: "button radius small" %>
  </div>

  <div class="row">
    <%= f.submit submit_text, class: "button medium radius success" %>
    <%= link_to "Cancel", root_path, class: "button medium radius secondary" %>
  </div>
<% end %>

app/views/categories/_subcategory_fields.html.erb
 <div class="row panel nested-fields">
  <div class="row">
    <div class="large-3 column">
      <%= f.label :name, "Subcategory Name" %>
      <%= f.text_field :name %>
    </div>

    <div class="large-1 column end">
      <%= link_to_remove_association "<i class='fi-x'></i>".html_safe, f, class: "button tiny radius alert", data: {confirm: "Are you sure? Note: won't be deleted for good until you update."} %>
    </div>
  </div>
  <div class="row panel" style="margin-bottom:2rem;">
    <strong>Exercises</strong>
    <%= f.fields_for :exercises do |exercises_fields| %>
      <%= render "exercise_fields", f: exercises_fields %>
    <% end %>
    <div class="row">
      <div class="large-1 column">
        <%= link_to_add_association "<i class='fi-plus'></i>".html_safe, f, :exercises, class: "button tiny radius success" %>
      </div>
    </div>
  </div>
</div>



<br>

app/views/categories/edit.html.erb
<%= render "shared/content_title", title: "Edit Category" %>

<%= render "form", submit_text: "Update" %>

app/views/categories/new.html.erb
<%= render "shared/content_title", title: "New Category" %>

<%= render "form", submit_text: "Create" %>

app/views/categories/show.html.erb
<%= render "shared/content_title", title: "#{@category.name}" %>
<div class="row">
  <div class=" large-6 large-centered column">
    <%= link_to "Edit", edit_category_path(@category), class: "button expand tiny warning radius" %>    
  </div>
</div>

<hr>
<% @category.subcategories.sort{|x,y| x.name <=> y.name}.each do |subcat| %>
  <table>
    <caption><%= "#{subcat.name}" %></caption>
    <thead>
      <tr>
        <th></th>
        <th>Exercise Name</th>
        <th>Nickname</th>
        <th><i class="fi-widget"></i></th>
      </tr>
    </thead>
    <tbody>
      <% count = 1 %>
      <% subcat.exercises.sort{|x,y| x.name <=> y.name}.each do |exercise| %>
      <tr>
        <td><%= count %></td>
        <% count += 1 %>
        <td><%= exercise.name %></td>
        <td><%= exercise.nickname %></td>
        <td>Future Button</td>
      </tr>
      <% end %>
      <% unless count > 1 %>
        <tr>
          <td colspan="4">Edit to Add an Exercise</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>