config/routes.rb
Rails.application.routes.draw do
  root 'teams#show_user_team'

  get '/register', to: 'teams#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :teams do
    resources :categories
  end

  resources :users do
    resources :cycles do
      resources :workouts, only: [:new, :create, :edit, :update]
    end
  end
  resources :categories

end

app/views/layouts/_footer.html.erb
<div id="footer" style="margin-top:100px;">
  <div class="row">
    <section class="text-center">
      <%= link_to "Workout Log", root_path %> by William J. Reilly &copy 2015
    </section>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div data-alert class="alert-box <%= name %>" style="margin-top:0.2rem;">
    <%= msg %>
    <%= link_to "#", class: "close" do%>
    &times;
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
  <% athletes = User.where(role: "Athlete").where(team: current_user.team).sort{|x,y| x.name <=> y.name} %>
  <% coaches = User.where(role: "Coach").where(team: current_user.team).sort{|x,y| x.name <=> y.name} %>
<% end %>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Workout Log</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <% if logged_in? %>
      <ul>
        <li class="has-dropdown not-click">
          <% categories = Category.where(team: current_user.team) %>
          <a href="#"><%= pluralize(categories.size, "Category")%></a>
          <ul class="dropdown">
            <li><%= link_to "Add Category", new_category_path %></li>
            <li class="divider"></li>
            

            <% categories.each do |cat| %>
              <li><%= link_to cat.name, category_path(cat)%></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="right">
        <li class="has-dropdown not-click">
          <%= link_to current_user.name, "#"%>
          <ul class="dropdown">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li> <%= link_to "Logout", logout_path%></li>
          </ul>
        </li>
        <% if ["Coach", "Admin"].include?(current_user.role) %>
          <li class="divider"></li>
          <li class="has-dropdown not-click">
            <a href="#"><%= pluralize(athletes.size, "Athlete")%></a>
            <ul class="dropdown">
              <% athletes.each do |athlete| %>
                <li class="has-dropdown">
                  <%= link_to athlete.name, user_path(athlete)%>
                  <ul class="dropdown">
                    <li><%= link_to "Add Cycle", new_user_cycle_path(athlete)%></li>
                    <li class="divider"></li>
                    <% athlete.cycles do |cycle| %>
                      <li><%= link_to cycle.description, user_cycle_path(athlete, cycle)%></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Add Athlete", new_user_path %></li>
            </ul>
          </li>
          <li class="divider"></li>
          <li class="has-dropdown not-click">
            <a href="#"><%= pluralize(coaches.size, "Coach")%></a>
            <ul class="dropdown">
              <% coaches.each do |coach| %>
                <li class="has-dropdown">
                  <%= link_to coach.name, user_path(coach)%>
                  <ul class="dropdown">
                    <li><%= link_to "Add Cycle", new_user_cycle_path(coach)%></li>
                    <li class="divider"></li>
                    <% coach.cycles.each do |cycle| %>
                      <li><%= link_to cycle.description, user_cycle_path(coach, cycle)%></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Add", new_user_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    <% else %>

      <ul class="right">
        <li class="divider"></li>
        <li>
          <%= link_to "Register", register_path%>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to "Login", login_path %>
        </li>
      </ul>
    <% end %>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Workout Log" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="row">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    
    <%= render "layouts/footer" %>
    <script type="text/javascript">
      $(function(){
        $(window).load(function() {
          $(document).foundation();
        });
      }); 
    </script>
  </body>
</html>